Pegasus.class: Pegasus.java Pet.java Emotion.java Unactive.java
	javac -g Pegasus.java
Pet.class: Pet.java
	javac -g Pet.java
Unactive.class: Unactive.java
	javac -g Unactive.java
Emotion.class: Emotion.java
	javac -g Emotion.java
run: Pegasus.class
	java Pegasus
clean:
	rm*.class
runPet: Pet.class
	java Pet
runUnactive: Unactive.class
	java Unactive
runEmotion: Emotion.class
	java Emotion
debug: Pegasus.class
	jbd Pegasus

